"""Criadas as tabelas enderecos, clientes e postagens.

Revision ID: 9ae9105108dc
Revises: 
Create Date: 2024-12-23 15:23:07.971289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ae9105108dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('client_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_cadastro', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(), nullable=False),
    sa.Column('client_secret', sa.String(), nullable=False),
    sa.Column('hash_token', sa.String(), nullable=False),
    sa.Column('token_expiracao', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('rua', sa.String(), nullable=False),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enderecos_id'), 'enderecos', ['id'], unique=False)
    op.create_table('postagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endereco_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('largura', sa.Float(), nullable=False),
    sa.Column('comprimento', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('valor_frete', sa.Float(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_postagem', sa.Enum('CRIADO', 'EM_TRANSITO', 'ENTREGUE', name='poststatus'), nullable=False),
    sa.Column('data_envio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previsao_entrega', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_entrega', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transportadora', sa.String(), nullable=False),
    sa.Column('codigo_rastreamento', sa.UUID(), nullable=False),
    sa.Column('historico_atualizacoes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_rastreamento')
    )
    op.create_index(op.f('ix_postagens_id'), 'postagens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postagens_id'), table_name='postagens')
    op.drop_table('postagens')
    op.drop_index(op.f('ix_enderecos_id'), table_name='enderecos')
    op.drop_table('enderecos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
